import '../cipher/scrambler.dart';

// Resolves credentials used by the attribution + push stack at runtime.
// All values are scrambled byte vectors generated by
// `tool/encode_keys.dart`. To rotate them, edit the plain values in the
// tool, run it, and paste the printed arrays here.
//
// IMPORTANT: leave the lists empty until the real values are provided.
// Each resolver below short-circuits to '' when its byte vector is
// empty, which lets the app boot offline-only without crashing.

// AppsFlyer Dev Key (Settings → Brand bundle → Dev Key).
String resolveAttributionKey() {
  const bytes = <int>[
    0x53, 0xd1, 0x46, 0xed, 0x7e, 0xd3, 0x55, 0xac,
    0xc7, 0x2e, 0x83, 0x2b, 0xeb, 0xa3, 0x59, 0x4c,
    0x55, 0x14, 0xe7, 0xc3, 0x5b, 0xe6,
  ];
  if (bytes.isEmpty) return '';
  return unscramble(bytes);
}

// Firebase Project Number (Project Settings → General → Project number).
// Distinct from the textual project ID — this is the all-digit one.
String resolveMessagingSenderId() {
  const bytes = <int>[
    0x27, 0x90, 0x37, 0x92, 0x7f, 0xb5, 0x5f, 0xad,
    0xb5, 0x6c, 0xe2, 0x50,
  ];
  if (bytes.isEmpty) return '';
  return unscramble(bytes);
}

// Builds the AppsFlyer Get-Conversion-Data REST URL used as the retry
// path when the SDK callback returns af_status == "Organic" on first
// fire (known SDK race on cold installs).
//
// Reference: https://dev.appsflyer.com/hc/reference/gcd-get-data
String resolveGcdEndpoint(String appId, String deviceId) {
  const host = <int>[
    0x76, 0xd4, 0x77, 0xd5, 0x34, 0xbb, 0x42, 0xb0,
    0xe6, 0x3c, 0xbf, 0x12, 0xee, 0x9a, 0x15, 0x7b,
    0x53, 0x0e, 0xc6, 0xcd, 0x72, 0xd9, 0x66, 0xd7,
    0x69, 0xe2, 0x02, 0xf2,
  ];
  const path = <int>[
    0x31, 0xc9, 0x6d, 0xd6, 0x33, 0xe0, 0x01, 0xf3,
    0xde, 0x3b, 0xba, 0x15, 0xeb, 0xde, 0x4d, 0x2e,
    0x0d, 0x4e, 0x9a,
  ];
  if (host.isEmpty) return '';
  return '${unscramble(host)}${unscramble(path)}$appId?device_id=$deviceId';
}
