import 'dart:typed_data';

// Byte-level scrambler for sensitive runtime strings (endpoint URLs,
// attribution dev key, messaging project id, etc.). Plain text never
// appears as a string literal in the compiled snapshot — only the
// encoded byte vectors do.
//
// The seed phrase below is unique to this title. Changing it forces a
// completely different XOR keystream and therefore different encoded
// arrays. Use `tool/encode_keys.dart` (which imports this file) to
// (re)generate the byte arrays after touching the seed.

// FeatherDash-specific seed: "feathr-go!" (10 chars). Picked so the
// derived key has no overlap with sibling apps under the same publisher.
const List<int> _seedBytes = <int>[
  0x66, 0x65, 0x61, 0x74, 0x68, 0x72, 0x2D, 0x67, 0x6F, 0x21,
];

// Length of the rotating key. Different from the sibling template's
// length so the derived bytes diverge entirely even with the same seed.
const int _keyLength = 20;

Uint8List _buildKeystream() {
  var state = 0x9E3779B1; // golden-ratio constant — Weyl-style mix
  for (final byte in _seedBytes) {
    state = ((state ^ byte) * 0x01000193) & 0xFFFFFFFF;
  }

  final keystream = Uint8List(_keyLength);
  for (var i = 0; i < _keyLength; i++) {
    state = ((state * 0x6C078965) + 0xB5297A4D) & 0xFFFFFFFF;
    state = state ^ (state >> 11);
    keystream[i] = (state >> 8) & 0xFF;
  }
  return keystream;
}

final Uint8List _key = _buildKeystream();

// Reverses the byte encoding produced by [scramble] into a UTF-8 string.
// Pass the byte arrays generated by `tool/encode_keys.dart`.
String unscramble(List<int> bytes) {
  if (bytes.isEmpty) return '';
  final decoded = Uint8List(bytes.length);
  for (var i = 0; i < bytes.length; i++) {
    decoded[i] = bytes[i] ^ _key[i % _key.length];
  }
  return String.fromCharCodes(decoded);
}

// Encodes a plaintext string into the byte vector used by [unscramble].
// Only invoked from `tool/encode_keys.dart`; never used at runtime.
List<int> scramble(String value) {
  final raw = value.codeUnits;
  final out = List<int>.filled(raw.length, 0);
  for (var i = 0; i < raw.length; i++) {
    out[i] = raw[i] ^ _key[i % _key.length];
  }
  return out;
}
